### ISSUE TITLE
Muse mastoid rereferencing?

### ISSUE THREAD

**Issue by DominiqueMakowski** [sccn/eeglab_musemonitor_plugin#1]
Hi Arnaud, first of all, thanks a lot for your youtube videos it's really really helpful!

In most tutorials the analysis proceeds with the default referencing, which is done on Fpz if I'm not mistaken.

Is there a reason not to re-reference the signal to mastoid (TP9 TP10)? 

A side likely-dumb question, if we re-reference, would it be somehow possible to "reconstruct" the Fpz channel from the data? 

Thanks again ☺️ and apologies in advance if that's not the best channel to ask

**Comment by arnodelorme** [comment]
Yes, you can reference to Mastoid if you want to. No about reconstructing Fpz. Cheers
